<!--Created By Nick Richardson-->
<!--IT 207-001, 2/12/2017-->
<p align = left><strong>Assignment List</p></strong>
        <ul>
            <a href = "/ModernApplicationsCollectionWebsite/FinalGradeCalculator/index.php"><li>Final Grade Calculator</li></a>
            <a href = "/ModernApplicationsCollectionWebsite/CalendarRegistration/index.php"><li>Calendar Registration</li></a>
            <a href = "/ModernApplicationsCollectionWebsite/ContactAddandUpdateSystem/index.php"><li>Contact Add and Update Sysytem</li></a>
            <a href = "/ModernApplicationsCollectionWebsite/ForumUsingMySQLandTextFile/index.php"><li>Forum using MySQL and Text File</li></a>
        </ul>
        <br>
        
        <ul>
            <a href = "../index.php"><li>Home</li></a>
        </ul>
</p>